### ISSUE TITLE
Once restarts error with beast or mlat data

### ISSUE THREAD

**Issue by andrew-savage** [mikenye/docker-graphs1090#16]
Once my computer restarts, I get major issues where the container wont load and is in a loop of restart and saying that the data is the same basically.

Here is my starting code:

```shell
docker run -d \
  --name=graphs1090 \
  --restart always \
  -p 8060:80 \
  -v graphs1090_rrd:/var/lib/collectd/rrd \
  -e TZ=Australia/Melbourne \
  -e BEASTHOST=192.168.1.202 \
  -e BEASTPORT=30005 \
  -e MLATHOST=192.168.1.202 \
  -e MLATPORT=30104 \
  -e LAT=<removed> \
  -e LONG=<removed> \
  mikenye/graphs1090:latest
```

Here is if I use docker compose:

```yaml
version: '2.0'

networks:
  adsbnet:

volumes:
  graphs1090_rrd:

services:
  graphs1090:
    image: mikenye/graphs1090:latest
    tty: true
    container_name: graphs1090
    restart: always
    volumes:
      - graphs1090_rrd:/var/lib/collectd/rrd
    ports:
      - 8060:80
    environment:
      - BEASTHOST=192.168.1.202
      - BEASTPORT=30005
      - TZ=Australia/Melbourne
      - LAT=<removed>
      - LONG=<removed>
    networks:
      - adsbnet
```

This is after I've removed the MLAT just to try it out.
<img width="422" alt="Capture" src="https://user-images.githubusercontent.com/72610825/95584712-e2fd9900-0a89-11eb-82e9-76870f1c4114.PNG">
